### ISSUE TITLE
config.js example

### ISSUE THREAD

**Issue by dicker182** [81RD/SmartMirror#5]
Hallo zusammen,

bin leider ein absoluter Neuling in Sachen Programmierung. Könnte mir jemand nur mal kurz ein Beispiel nennen wir man das Wetter aktiviert bekommt? Mit Values und Methods bin ich noch nicht vertraut. Arbeite aber dran :)

Viele Grüße
Dicker182

**Comment by 3DJupp** [comment]
https://github.com/Dom1n1c/Smartmirror/tree/Version1
Is a project based on this. 

You need to enter an Openweathermap APIKEY,
(P.S.: Spreche auch deutsch, aber falls noch jemand die gleiche frage hat... dann ist das sicher besser)

**Comment by dicker182** [comment]
Danke!
